apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openwebui
  template:
    metadata:
      labels:
        app: openwebui
    spec:
      serviceAccountName: jenkins
      containers:
        - name: openwebui
          image: {{AWS_ACCOUNT_ID}}.dkr.ecr.{{AWS_REGION}}.amazonaws.com/{{IMAGE_NAME}}:{{IMAGE_TAG}}
          imagePullPolicy: "Always"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: ecr-secret
