apiVersion: v1
kind: Deployment
metadata:
  name: openwebui
spec:
  serviceAccountName: jenkins
  containers:
    - name: openwebui
      image: {{AWS_ACCOUNT_ID}}.dkr.ecr.{{AWS_REGION}}.amazonaws.com/{{IMAGE_NAME}}:{{IMAGE_TAG}}
      ports:
        - containerPort: 80
  imagePullSecrets:
    - name: ecr-secret
